"""create_atendimentos_table

Revision ID: b9b49dfef60e
Revises: 20260530_0006
Create Date: 2026-07-02 19:02:13.770640

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9b49dfef60e'
down_revision: str | None = '20260530_0006'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('atendimentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='em_andamento', nullable=False),
    sa.Column('data_inicio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('data_fim', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('planejado', 'em_andamento', 'concluido', 'cancelado')", name='ck_atendimentos_status_valid'),
    sa.ForeignKeyConstraint(['tecnico_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['chamados.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atendimentos_id'), 'atendimentos', ['id'], unique=False)
    op.create_index(op.f('ix_atendimentos_tecnico_id'), 'atendimentos', ['tecnico_id'], unique=False)
    op.create_index(op.f('ix_atendimentos_ticket_id'), 'atendimentos', ['ticket_id'], unique=False)
    op.drop_index(op.f('ix_chamados_cliente_id'), table_name='chamados')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_chamados_cliente_id'), 'chamados', ['owner_id'], unique=False)
    op.drop_index(op.f('ix_atendimentos_ticket_id'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_tecnico_id'), table_name='atendimentos')
    op.drop_index(op.f('ix_atendimentos_id'), table_name='atendimentos')
    op.drop_table('atendimentos')
    # ### end Alembic commands ###
